# Generated by Django 4.0.4 on 2022-11-21 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_testresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststatement',
            name='compiler',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('input', models.CharField(blank=True, max_length=255, null=True)),
                ('output', models.CharField(blank=True, max_length=255, null=True)),
                ('testStatement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testCases', to='myapp.teststatement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
