# Generated by Django 4.0.4 on 2022-12-07 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_teststatement_compiler_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imageurl',
            field=models.URLField(default=57, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='isUser',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('company', 'Company')], default='candidate', max_length=50),
        ),
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobmodel')),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.test')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
