# Generated by Django 4.0.4 on 2022-12-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_user_imageurl_user_isuser_jobapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imageurl',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
