# Generated by Django 4.0.4 on 2022-12-20 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_user_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='user_id',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='company_name',
            field=models.CharField(max_length=255, null='True'),
        ),
        migrations.AlterField(
            model_name='teststatement',
            name='testId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='myapp.test'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=50, null='True'),
        ),
        migrations.CreateModel(
            name='Total_Applications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.TextField(choices=[('Completed', 'Completed'), ('Started', 'Started'), ('InProgress', 'InProgress')], default='Started', max_length=255)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.test')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='myapp.jobmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Company_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobmodel')),
            ],
        ),
    ]
