# Generated by Django 4.0.4 on 2023-01-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_jobmodel_user_id_user_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isUser',
            field=models.CharField(blank=True, choices=[('candidate', 'Candidate'), ('company', 'Company')], default='candidate', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
