# Generated by Django 4.0.4 on 2023-01-17 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('working_hours', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('salarytype', models.CharField(choices=[('Per Year', 'Per Year'), ('Per Month', 'Per Month')], default='per year', max_length=255)),
                ('currency', models.CharField(choices=[('Rs/-', 'Rs/-'), ('$', '$'), ('€', '€')], default='rupee', max_length=255)),
                ('jobtype', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Internship', 'Internship')], default='full-time', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('tests', models.ManyToManyField(related_name='jobs', to='myapp.test')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='company_details',
            name='Job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.job'),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='Job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.job'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='Job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.job'),
        ),
        migrations.AlterField(
            model_name='total_applications',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='myapp.job'),
        ),
        migrations.DeleteModel(
            name='JobModel',
        ),
    ]
