# Generated by Django 4.0.4 on 2023-01-17 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_job_alter_company_details_job_alter_jobapply_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='Job',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.job'),
        ),
    ]
