# Generated by Django 4.0.4 on 2023-01-17 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_company_details_job_alter_jobapply_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='company',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.company'),
            preserve_default=False,
        ),
    ]
