# Generated by Django 4.0.4 on 2023-01-17 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_test_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company'),
        ),
    ]
