# Generated by Django 4.0.4 on 2023-01-20 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_alter_test_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.TextField(choices=[('Completed', 'Completed'), ('Started', 'Started'), ('InProgress', 'InProgress')], default='Started', max_length=255)),
                ('ResultPercentage', models.IntegerField(blank=True, null=True)),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.job')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AlterField(
            model_name='testresult',
            name='Job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.appliedjobs'),
        ),
    ]
