# Generated by Django 4.0.4 on 2023-01-20 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_appliedjobs_alter_testresult_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='Jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.appliedjobs'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='Job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.job'),
        ),
    ]
